name: MalloyEvents
favicon: null
layout_spectrum: 0.74406
typography_spectrum: 0.03382
title: Custom Events.  Design.Plan. Execute
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#919191'
    - '#ffffff'
    - '#c9c9c9'
    - '#474747'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
